---
title: "SDGs"
author: "Nina Hauser"
date: "11/25/2021"
output: html_document
---

```{r setup, include=FALSE}
# Schritt 1: Infrastruktur
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

# Notwendige Packages laden
library(tidyverse)
```

```{r datenimport, include = FALSE}
# Schritt 2: Daten laden
### Plastics-Daten laden
plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')

# Daten der World Bank mit R-Package ziehen
wb_protectedareas <- WDI::WDI(
  country = "all", # Auswahl der Länder
  indicator = "ER.PTD.TOTL.ZS",  # Spezifikation des Indikators (Tipp: siehe Link in der Datenbank)
  start = 2018, # Auswahl Zeithorizont: Anfang
  end = 2018, # Auswahl Zeithorizont: Ende
  language = "en" # Sprachauswahl
) 

# Daten mit dem SDGsR-Package laden (optional)
sdg_daten1251 <- SDGsR::get_indicator_data(indicator = "12.5.1")
```

```{r}
# Filtern der SDG-Daten für die letzte Eintragung
sdg_daten1251_clean <- sdg_daten1251 %>%
  dplyr::filter(seriesDescription == "Municipal waste recycled (Tonnes)") %>%
  dplyr::select(c("geoAreaName", "timePeriodStart", "value")) %>% # Auswahl relevanter Spalten
  dplyr::arrange(geoAreaName, desc(timePeriodStart)) %>% # Sortierung nach geographischer Lage und Erhebungszeitraum
  dplyr::group_by(geoAreaName) %>% # Gruppierung nach geographischer Lage
  dplyr::slice_head(n = 1) # Filtern der nach Zeit sortierten Werte ("Nimm den ersten"), sodass der aktuellste Wert pro geographischer Lage erhalten bleibt
```

