## **Setup**

Zwar legen wir diese Woche nicht direkt mit Coden los, aber bevor es auch wirklich losgehen kann, benötigt Ihr zwei Dinge:

- [R](https://ftp.fau.de/cran/){target="_blank"}, also die freie, statistische Programmiersprache an sich
- [RStudio](https://rstudio.com/products/rstudio/download/#download){target="_blank"}, also die auf R spezialisierte integrierte Entwicklungsumgebung (im Prinzip die Benutzeroberfläche)

Versucht gerne einmal selbst, die beiden Programme für Euer Betriebssystem zu installieren – idealerweise auf einem Laptop oder PC, auf dem Ihr **Adminrechte** habt. Bei Installationsschwierigkeiten könnt Ihr uns gerne **per E-Mail oder Slack-Nachricht** an Zoé (zoe.w@correlaid.org) kontaktieren - dann lösen wir die Herausforderungen mit Euch gemeinsam.

Links seht ihr außerdem schon das **Glossar**. Noch wird Euch vielleicht vieles davon noch unbekannt vorkommen und Ihr müsst das auch nicht komplett durcharbeiten. Schaut hier aber immer mal wieder vorbei in den nächsten Wochen, hier verstecken sich bestimmt hilfreiche Informationen! 

<p style="border-width:1px; border-style:solid; border-color:#acc940; padding: 1em;">
  **Disclaimer** <br>
  In den nächsten Wochen wird Euch sehr viel Neues begegnen, in manchen Wochen mehr und in anderen weniger. In manchen Wochen werdet Ihr länger brauchen als gedacht, in anderen geht es vielleicht ganz fix. Lasst Euch nicht entmutigen, wenn Ihr etwas nicht direkt versteht oder Euch eine Woche erschlägt, damit seid Ihr nicht alleine! Tauscht Euch gerne in Euren Lernduos aus, meldet Euch bei Eurer Mentorin oder Eurem Mentor und bringt Eure Fragen mit zu den Livesessions - dazu mehr auch nächste Woche in der ersten Livesession am Freitag!
</p>
