## Glossar

``` {r settings_glossar, echo=FALSE, include=FALSE}
```

Da man in dem **Fachwortdschungel der Datenwissenschaft** gerne mal verloren gehen kann, pflegen wir hier für Euch ein Glossar, das unsere Tutor:innen nach und nach für Euch mit wichtigen Begrifflichkeiten füllen werden. <br>
Zusätzlich erstellen wir für Euch an dieser Stelle eine Übersicht zu den wichtigsten Syntaxregeln und Funktionen.

Zum Begriffsdschungel gab es bei uns übrigens schon einmal ein Open Online Data Meetup (OODM) - zur Aufzeichnung geht es [hier](https://www.youtube.com/watch?v=HhH6nOQmqa0){target="_blank"}.

### Technische Fachbegriffe

**Absolute Häufigkeit** = Anzahl der Ausprägungen

**Ausreißer** = Beobachtung, die von anderen Beobachtungen auffällig abweicht

**Dashboard** (zu dt. Instrumententafel) = Zusammenstellung von (zumeist) explorativen Datenanalyseelementen wie Visualisierungen und statistischen Kennwerten 

**Dataframe** (zu dt. Datenrahmen) = tabellarisches Objekt, in dem Daten gespeichert werden 

**Daten** = formalisierte, idealerweise durch Binärcodierung maschinell lesbare Informationen 

**Datenwissenschaft** = Werkzeug zur Verarbeitung von Daten, Denkweise ("Wie gehen wir an Herausforderungen heran?") und Kompetenzbereich ("Welche analytischen, technischen und fachlichen Fähigkeiten sind notwendig?")

**Dimension eines Datensatzes** = Anzahl an Beobachtungen (Zeilen) und Anzahl an Variablen (Spalten)

**Dokumentation (von Code)** = Abrufbare Informationen zu Packages, Funktionen und Argumenten

**DSGVO** = verfassungsrechtlich verankertes Grundrecht, das personenbezogene Daten vor Missbrauch schützt (Art. 1 Abs. 1 und Art. 2 Abs. 1 GG, Art. 1 - 4 ff. DSGVO)

**Environment (RStudio** = Ort der IDE RStudio, in dem Objekte gespeichert werden 

**Framework** = Grundgerüst zur Programmierung von Applikationen

**Git** = Kollaborationstool für Informatiker:innen, über das wir Code und Daten austauschen

**Granularität** = Konzept der Datenwissenschaft, nach dem Daten idealerweise pro individuellem Subjekt vorliegen (in unserem R Lernen Kurs also pro Teilnehmer:in) und nicht aggregiert (also z.B. als aggregierte Anzahl von Teilnehmer:innen pro Live Session)

**Image Recognition** (zu dt. Bilderkennung) = Automatisierte Verarbeitung und Interpretation von Bilddateien 

**Integrierte Entwicklungsumgebung** (kurz: IDE) = Umgebung für das Schreiben und die Interpretation von Code

**Median** = robuster "Mittelpunkt" mehrerer Zahlen (50% der Ausprägungen sind kleiner oder größer)

**Mittelwert** = Durchschnittswert einer Menge aus mehreren Zahlen

**Modus (auch: Modalwert)** = häufigster Wert in einer Menge an Zahlen

**Open Source Software** = frei nutzbare, unlizenzierte Software (aber eventuell mit Verpflichtung zur Autor:innenkennung)

**Packages** (zu dt. Pakete) = Bündel an programmierten, wiederverwendbaren Funktionalitäten

**Relative Häufigkeit** = Prozentualer Anteil der Ausprägungen in einer Gruppe

**R Markdown** = RStudio-Dateiformat zur Kombination von Code und Text mit Exportfunktionalitäten zu PDF und HTML

**Robustheit** = Insensibilität gegenüber *Ausreißern*

**RProject** = Tool zur Dateibündelung von Codeskripten, Daten uvm. für das vereinfachte Teilen von Programmierprojekten

**Shiny Web App** = *Framework* zur Programmierung von interaktiven *Dashboards* in R

**Slicing** = Zugriff auf bestimmte Daten in einem *Dataframe*

**Standardabweichung** = standardisiertes Maß für die Streuung um den Mittelwert

**Subsets** = Teilmenge des Datensatzes

**Variable Assignment** (zu dt. Variablenzuweisung) = Benennung von Objekten (in R durch "objektname <- objekt)

**Varianz** = Streuung um den *Mittelwert*

**Work Space** (zu dt. Arbeitsspeicher) = Temporärer Arbeitsspeicher der *IDE* während der Programmierung (nie speichern)


### Wichtiger Syntax in R

**Code Chunk** <br>
\```{r} <br>
Dein Code hier <br>
\``` <br>

**Funktion** <br>
package::funktion(argument1, argument2, ...) <br>

**Konditionale Statements** <br>
if ( test_expression1) { <br>
  statement1 <br>
  } else if ( test_expression2) { <br>
  statement2 <br>
  } else if ( test_expression3) { <br>
  statement3 <br>
  } else { <br>
  statement4 <br>
}

**Logische Ausdrücke** <br>
*Hinweis: Der Output von logischen Ausdrücken ergibt "TRUE" (wahr) oder "FALSE" (falsch)* <br>
Variable == "Ausdruck" (ist gleich) <br>
Variable1 < Variable 2 (kleiner als) <br>
Variable1 <= Variable 2 (kleiner gleich) <br>
Variable1 > Variable 2 (größer als) <br>
Variable1 >= Variable 2 (größer gleich) <br>

**Pipe-Operator (zum Zusammenfügen von Operationen** <br>
%>% (im Rahmen des tidyverse) <br>
|> (der generelle Pipeoperator) <br>

**Variablenzuweisung** <br>
objektname <- objekt <br>

**Zugriff auf Daten/Zeilen/Spalten in Dataframes** <br>
*Hinweis: In R fängt man bei 1 an zu zählen - nicht wie in anderen Programmiersprachen bei 0* <br>
dataframe[zeilennummer,spaltennummer] <br>
dataframe[zeilennummer,] <br>
dataframe[,spaltennummer] <br>
dataframe[beginnzeile:endezeile, beginnspalte:endespalte] <br>

**Zugriff auf Variablen (Spalten) über den Namen in Dataframes** <br>
datensatz$variablenname <br>
datensatz['variablenname'] <br>

**Zugriff auf Subsets in Dataframes** <br>
*Hinweis: In R fängt man bei 1 an zu zählen - nicht wie in anderen Programmiersprachen bei 0* <br>
dataframe[beginnzeile:endezeile, beginnspalte:endespalte] <br>
subset(dataframe, ausdruck) <br>

### Wichtige Packages in R
Neben den Grundfunktionen ("baseR") benötigt für Eure Arbeit in R oft weitere Funktionen. Diese findet Ihr in sog. Packages:

`library(dplyr)` - Package zur Datenbereinigung und Berechnung statistischer Kennzahlen <br>
`library(ggplot2)` - Package zur Visualisierung von Daten <br>
`library(rio)` - Package zum vereinfachten Laden von Daten <br>
`library(tidyverse)` - Packagesammlung für die Datenwissenschaft <br>

### Wichtige Funktionen in R

**Anzahl** = `n()`

**Auswahl von Spalten** (Variablen) = `dplyr::select()`

**Auswahl von Zeilen** (Beobachtungen) nach Kriterien = `dplyr::filter()`

**(minimale/maximale) Ausprägung** einer Variablen = `min()`/`max()`

**Berechnung neuer Spalten** (Variablen) auf Basis vorhandener Variablen = `dplyr::mutate()`

**(Partiellen) Datensatz anzeigen** = `View()`/`head()`/`tail()`

**(tagesaktuelles) Datum** = `Sys.Date()`

**Dimension** = `dim()`

**Einlesen von Dateien** = `rio::import()`

**Gruppierung von Zielen** (Beobachtungen) nach Kriterien = `dplyr::group_by()`

**Hilfe** = `help("")`/`?funktion`

**Installation von Packages** = `install.packages("") `

**Laden von Packages** = `library()`

**Mittelwert, Median und Modus** = `mean()`/`median()`/`mode()`

**Sortierung von Zeilen** nach Kriterien = `dplyr::arrange()`

**Spaltenanzahl** = `ncol()`

**Standardabweichung** = `sd()`

**Subsets** = `subset()`

**Summe** = `sum()`

**Übersicht über Datensatz** = `summary()`/`str()`/`dplyr::glimpse()`

**Variablennamen anzeigen** = `colnames()`

**Varianz** = `var()`

**(Erstellung einer) Visualisierung** = `ggplot2:ggplot(data = , aes(x = , y = ))`

**Zeilenanzahl** = `nrow()`

**Zusammenfassung von Werten** zur Vereinfachung des Informationsgehalts = `dplyr::summarize()`
