---
title: "Inhaltsverzeichnis"
author:
output: 
  learnr::tutorial:
    includes:
      after_body: ./www/favicon.html
    language: de
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
# remotes::install_github("rstudio/learnr")
# remotes::install_github("rstudio/gradethis")
library(gradethis)
library(learnr)
library(rio)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(janitor)
library(countrycode)
library(haven)
library(httr)
library(purrr)
library(RSQLite)
library(DBI)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
gradethis::gradethis_setup(pass = "Gut gemacht!", 
                           fail = "Das ist leider nicht ganz richtig. Probiert es nochmal!",
                           code_correct = "Gut gemacht!", 
                           code_incorrect = "Das ist leider nicht ganz richtig. Probiert es nochmal!",
                           maybe_code_feedback = FALSE,
                           fail.hint = FALSE,
                           grading_problem.message = "Hups. Ist hier Code zur Überprüfung? Wenn ja, dann liegt der Fehler bei uns. Schickt Nina bitte einen Screenshot mit der Übung und Eurer Lösung."
                           )
### Daten laden
plastics <- rio::import('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')

# Daten der World Bank mit R-Package ziehen
wb_areas <- WDI::WDI(
  country = "all", # Auswahl der Länder
  indicator = "ER.PTD.TOTL.ZS",  # Spezifikation des Indikators (Tipp: siehe Link in der Datenbank)
  start = 2018, # Auswahl Zeithorizont: Anfang
  end = 2018, # Auswahl Zeithorizont: Ende
  language = "en" #Sprachauswahl
) 
data_wb <- wb_areas %>% 
  dplyr::select(country_code = 'iso2c',
                protected_area = 'ER.PTD.TOTL.ZS'
                )

# Einlesen der Shapefiles
polygons_welt <- sf::st_read(here::here("daten/geospatial/ne_50m_admin_0_countries.shp"))
polygons_deutschland <- sf::st_read(here::here("daten/geospatial/1000_NUTS1.shp"))

# Initialisierung eines temporären Ordners
tmpfile <- tempfile(fileext = "sqlite") # Identifizierung der SQLite-DB über das Suffix "sqlite"
download.file("https://correlaid.github.io/lernplattform/daten/plastics.sqlite", tmpfile) # Herunterladen der temporären Datei
con <- dbConnect(RSQLite::SQLite(), tmpfile) # Aufbau der Verbindung

# API
basis_url <- "https://unstats.un.org/" # Haupt-URL
initiale_anfrage <- httr::GET( # Initialisierung
  basis_url, # URL verlinken
  path = "/SDGAPI/v1/sdg/Series/Data", # Route definieren
  query = list(
    seriescode = "EN_REF_WASCOL"
  )
)

# Vorläufig Inhalt der Inititalabfrage zur Prüfung speichern
content <- httr::content(initiale_anfrage)

# Einlesen der Seitenanzahl durch das Attribut "totalPages", auf das wir mithilfe von "$" zugreifen
total_pages <- content$totalPages
pages <- c(1:total_pages)

# Inhalt der Response herausziehen
waste_data <- httr::content(initiale_anfrage)

# Für verschiedene Städte in verschiedenen Ländern erhalten wir so zu verschiedenen Jahren Ihre Müllsammlungsquoten
waste_list <- waste_data$data

# Mit dem purrr-Package ziehen wir nun die Daten in einen Dataframe
waste_geo <- waste_list %>%
  purrr::map_df(`[`, c("geoAreaCode", "geoAreaName", "dimensions", "value")) %>%
  filter(dimensions != "G") # Duplikate entfernen, die aus der Datenstruktur resultieren

### Daten bereinigen
# Country name cleaning: 
  # United Kingdom of Great Britain & Northern Ireland sowie für die USA
plastics_prep <- plastics %>%
  # nur 2019 weil 2020 wegen der Pandemie ein nicht repräsentatives Jahr ist
  filter(year==2019) %>%
  mutate(country = str_replace(country, "United Kingdom of Great Britain & Northern Ireland", "United Kingdom"),
         country = str_replace(country, "United States of America", "United States"),
         country = str_to_title(country) ) %>% #um z.B.: ECUADOR etc case ändern
  #Continent und Country Code anspielen
  mutate(continent = countrycode::countrycode(country, origin = "country.name", destination = "continent"),
         countrycode = countrycode::countrycode(country, origin = "country.name", destination = "iso3c")) %>%
  mutate(continent=replace_na(continent, "Unknown"),
         countrycode=replace_na(countrycode, "Unknown"))

### Community Datensatz erstellen
community<- plastics_prep %>%
  select(country, year, num_events, volunteers, grand_total, continent, countrycode) %>%
  group_by(country, year) %>%
  filter(row_number()==1)
#write.csv(community, here::here("daten/community_perspective.csv"), row.names = FALSE)

# Audit Plastik Datensatz erstellen
audit_plastic<- plastics_prep %>%
  # nur grandtotal zeile behalten
  filter(parent_company=="Grand Total") %>%
  select(-c(parent_company, num_events, volunteers, empty)) %>%
  #NA zu 0
  mutate(
    across(everything(), ~replace_na(.x, 0))
  )
#write.csv(audit_plastic, here::here("daten/audit_perspective.csv"), row.names = FALSE)

# EU-Asien Audit Plastik Datensatz erstellen
audit_plastic_eu_asia<- audit_plastic %>%
  filter(continent == "Europe" | continent == "Asia") %>%
  group_by(country) %>%
  mutate(n_types=sum(c(hdpe, ldpe, o, pet, pp, ps, pvc)!=0))

# Datensätze für 2019 & 2020 & reduziert
plastics_2019 <- plastics %>%
  dplyr::filter(year == "2019") 
plastics_2020 <- plastics %>%
  dplyr::filter(year == "2020") 
plastics_reduced <- plastics_2019 %>%
  dplyr::select(-grand_total)
reduced_2019 <- plastics_2019 %>%
  dplyr::filter(parent_company != "Grand Total" 
                & country != "EMPTY") %>%
  dplyr::group_by(country) %>%
  dplyr::summarize(grand_total = sum(grand_total),
                   num_events = mean(num_events),
                   volunteers = mean(volunteers))
reduced_2020 <- plastics_2020 %>%
  dplyr::filter(parent_company != "Grand Total"
                & country != "EMPTY") %>%
  dplyr::group_by(country) %>%
  dplyr::summarize(grand_total = sum(grand_total),
                   num_events = mean(num_events),
                   volunteers = mean(volunteers))
data_no_na <- na.omit(reduced_2020)
data_2019 <- reduced_2019
data_2019$country_code <- countrycode::countrycode(data_2019$country, origin = 'country.name',
                                                   destination = 'iso2c')


# Mini-Datensätze für NA's
df <- tibble::tribble(
  ~name,              ~x,  ~y,           ~z,  
  "Person 1",         1,   -99,          6.7, 
  "Person 2",         3,   NA,           -99,
  "Person 3",         NA,  0.76,         -1.6
  )
df2 <- df %>% 
  dplyr::na_if(-99)

# Exportieren der Datensets in CSV für DB
# Country Codes
country_db <- community %>%
  ungroup() %>%
  select(countrycode, country, continent)
#write.csv(country_db, here::here("daten/country.csv"), row.names = FALSE)

# Community
community_db <- community %>%
  ungroup() %>%
  select(countrycode, year, num_events, volunteers)
#write.csv(community_db, here::here("daten/community.csv"), row.names = FALSE)

# Audit Plastic
audit_db <- plastics_prep %>%
  filter(parent_company != "Grand Total") %>% 
  ungroup() %>%
  select(-c(country, continent, num_events, volunteers, grand_total, empty)) %>%
  pivot_longer(c("hdpe", "ldpe", "o", "pet", "pp", "ps", "pvc")) %>%
  filter(parent_company != "Grand Total")
write.csv(audit_db, here::here("daten/audit_plastics.csv"), row.names = FALSE)
``` 


```{r results='asis'}
out <- knitr::knit_child("00_intro.Rmd", quiet = TRUE)
cat(out, sep = '')
```

```{r results='asis'}
out <- knitr::knit_child("01_datenprojekte.Rmd", quiet = TRUE)
cat(out, sep = '')
```

```{r results='asis'}
out <- knitr::knit_child("02_datenstrategie.Rmd", quiet = TRUE)
cat(out, sep = '')
```

```{r results='asis'}
out <- knitr::knit_child("03_datenschutz.Rmd", quiet = TRUE)
cat(out, sep = '')
```

```{r results='asis'}
out <- knitr::knit_child("04_rstudio.Rmd", quiet = TRUE)
cat(out, sep = '')
```

```{r results='asis'}
out <- knitr::knit_child("05_Erste_Analysen.Rmd", quiet = TRUE)
cat(out, sep = '')
```

```{r results='asis'}
out <- knitr::knit_child("06_datenimport_NH.Rmd", quiet = TRUE) 
cat(out, sep = '')
```

```{r results='asis'}
out <- knitr::knit_child("06_datenimport_exkursapi.Rmd", quiet = TRUE) 
cat(out, sep = '')
```

```{r results='asis'}
out <- knitr::knit_child("06_datenimport_exkurssql.Rmd", quiet = TRUE) 
cat(out, sep = '')
```

```{r results='asis'}
out <- knitr::knit_child("07_datenbereinigung.Rmd", quiet = TRUE)
cat(out, sep = '')
```

## Reports in R Markdown
```{r results='asis'}
out <- knitr::knit_child("08_Reports.Rmd", quiet = TRUE)
cat(out, sep = '')
```

## Reportautomatisierungen
```{r results='asis'}
#out <- knitr::knit_child("09_AutomatisierteReports", quiet = TRUE)
#cat(out, sep = '')
```

## Datenvisualisierung
```{r results='asis'}
# out <- knitr::knit_child("10_Shiny1", quiet = TRUE)
# cat(out, sep = '')
```

## Interaktive Visualisierungen
```{r results='asis'}
#out <- knitr::knit_child("11_Shiny2", quiet = TRUE)
#cat(out, sep = '')
```

## Und jetzt?
```{r results='asis'}
#out <- knitr::knit_child("12_closing.Rmd", quiet = TRUE)
#cat(out, sep = '')
```

```{r results='asis'}
out <- knitr::knit_child("99_glossar.Rmd", quiet = TRUE)
cat(out, sep = '')
```
