---
author: "Lisa Reiber"
date: "19 11 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(
  tidyverse,
  rio,
  tidylog
)
```

```{r import-data}
# plastics <- # Hier Euer Code! #TODO for now
plastics_raw <- rio::import('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')
```

```{r process-data}
plastics_processed <- plastics_raw %>%
  # drop empty countries
  dplyr::filter(
    country != "EMPTY",
    parent_company != "Grand Total"
    ) %>%
  # clean country names
  dplyr::mutate(
    country =
      dplyr::case_when(
        country == "United Kingdom of Great Britain & Northern Ireland" ~ "United Kingdom",
        country == "United States of America" ~ "United States",
        TRUE ~ country
      ),
    # Strings to title um z.B.: ECUADOR etc case ändern
    country = str_to_title(country),
    #Continent und Country Code anspielen
    continent = countrycode::countrycode(country,
                                         origin = "country.name",
                                         destination = "continent"),
    countrycode = countrycode::countrycode(country,
                                           origin = "country.name",
                                           destination = "iso3c"),
    # Replace NA's
    continent = tidyr::replace_na(continent, "Unknown"),
    countrycode = tidyr::replace_na(countrycode, "Unknown")
    ) 
```

```{r reshape-data}
community19_by_country <- plastics_processed %>% 
  dplyr::filter(year == 2019) %>% 
  dplyr::group_by(continent, country) %>% 
  dplyr::summarize(
    n_pieces = sum(grand_total, na.rm = TRUE),
    n_volunteers = unique(volunteers),
    n_events = unique(num_events)
    ) %>% 
  dplyr::add_count(name = "total_pieces", wt = n_pieces) %>%
  dplyr::ungroup() %>% 
  dplyr::mutate(
    rel_freq = round(n_pieces/total_pieces, 3)
    )

plastics19 <- plastics_processed %>%
  filter(year == 2019) %>% 
  tidyr::pivot_longer(
    cols = c(hdpe, ldpe, o, pet, pp, ps, pvc),
    names_to = "plastic_type",
    values_to = "n_pieces"
    ) %>%
  dplyr::mutate(dplyr::across(
    .cols = c(country, continent, year, plastic_type),
    .fns = as_factor
    )) %>%
  dplyr::select(
    # year,
    continent,
    country,
    parent_company,
    plastic_type,
    n_pieces,
    total_per_country = grand_total,
    ) %>% 
  # relative Anteile berechnen
  dplyr::mutate(
    rel_freq = round(n_pieces / total_per_country, 3)
  ) 

plastics19_by_continent <- plastics19 %>% 
  dplyr::group_by(continent, plastic_type) %>% 
  dplyr::summarize(
    n_pieces = sum(n_pieces, na.rm = TRUE)
    ) %>% 
  dplyr::add_count(name = "total_pieces", wt = n_pieces) %>%
  dplyr::ungroup() %>% 
  dplyr::mutate(
    rel_freq = round(n_pieces/total_pieces, 3)
    ) 
```

```{r export-data}
plastics19_by_continent %>% rio::export(here::here("daten/plastics19_by_continent.rds"))
community19_by_country %>% rio::export(here::here("daten/community19_by_country.rds"))
plastics19 %>% rio::export(here::here("daten/plastics19_long.rds"))
```

