---
params:
  country: "Canada"
output: html_document
---

```{r}
```


```{r setup, include=FALSE}
# Schritt 1: Infrastruktur
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

# Notwendige Packages laden
library(tidyverse)
title <- paste("L채nderbericht", params$country)
```

---
title: `r title`
---

```{r datenimport, include = FALSE}
# Schritt 2: Daten laden
### Daten laden
plastics <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv")

# Schritt 3: Daten bereinigen
# Country name cleaning:
# United Kingdom of Great Britain & Northern Ireland sowie f체r die USA
plastics_prep <- plastics %>%
  # nur 2019 weil 2020 wegen der Pandemie ein nicht repr채sentatives Jahr ist
  filter(year == 2019) %>%
  mutate(
    country = str_replace(
      country,
      "United Kingdom of Great Britain & Northern Ireland",
      "United Kingdom"
    ),
    country = str_replace(country, "United States of America", "United States"),
    country = str_to_title(country)
  ) %>% # um z.B.: ECUADOR etc case 채ndern
  # Continent und Country Code anspielen
  mutate(
    continent = countrycode::countrycode(country, origin = "country.name", destination = "continent"),
    countrycode = countrycode::countrycode(country, origin = "country.name", destination = "iso3c")
  ) %>%
  mutate(
    continent = replace_na(continent, "Unknown"),
    countrycode = replace_na(countrycode, "Unknown")
  )
```

```{r}
country_data <- plastics_prep %>%
  filter(country == params$country)
```

- ideen: 
  - verschiedene plastikarten anteilig in kanada vs world oder continent
  - text mit inline r (so und so viele volunteers und events, summe plastik gesammelt)
  
