---
title: "04_rstudio_livesession"
author: "Zoé Wolter"
date: "29 7 2022"
output: html_document
---

# Live-Session 29.07.2022
## R Lernen - Der Datenkurs von und für die Zivilgesellschaft

### Setup

Zuerst steht der **Set-up-Code Chunk**, in dem Ihr global (= also für das gesamte Dokument) Einstellungen vornehmen könnt. Beispielsweise Packages können hier installiert *und* geladen werden!

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, include = TRUE)

# Installation und Laden des Packages "rio"
# install.packages("rio")
library(rio)
```

### Basic Syntax

```{r variablen}
# Über einen Pfeil werden Werte zu Variablen hinzugefügt
zahl <- 2
zahlen <- c(1, 2, 3, 4)
```

```{r math}
# R ist ein Taschenrechner!
2 + 2 # plus
2 - 1 # minus
2 * 2 # mal
2 / 2 # geteilt
2 %% 3 # Modulo
```

```{r logical}
# R kann Logik!
2 == 2 # ist gleich
2 != 3 # nicht gleich
!(2 == 2) # nicht
2 < 3 # kleiner als
2 > 3 # größer als
2 <= 2 # kleiner gleich
2 >= 3 # größer gleich
(1 + 1 == 2) & (2 + 2 == 5) # und
(1 + 1 == 2) | (2 + 2 == 5) # oder
```

### Kontrollstrukturen: If & Loop

```{r if_else}
# Wenn-Dann-Ausdrücke
if (2 + 2 == 5) {
  print("Oh nein!")
} else if (2 + 2 <= 3) {
  print("Oh nein!")
} else if (2 + 2 >= 5) {
  print("Oh nein!")
} else {
  print("Puh, nicht verrechnet...")
}
```

```{r for_loop}
# Schleifen auf Basis einer bekannten Anzahl an Wiederholungen
# (hier drei Elemente der Liste)
for (spender_in in list("Phil", "Frie", "Nina")) {
  print(paste("Danke,", spender_in, "!"))
}
```

```{r while_loop}
# Schleifen auf Basis einer Bedingung
# (und einer somit unbekannten Anzahl)
spender_innenliste <- list("Phil", "Frie", "Nina")
i <- 1
while (i <= length(spender_innenliste)) {
  print(paste("Danke,", spender_innenliste[[i]], "!"))
  i <- i + 1
}
```

### Datenimport

``` {r einlesen}
# Alternative 1: direkt über URL
plastics <- rio::import("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv", fill = TRUE)

# Alternative 2: aus lokal gespeicherter Datei
plastics <- rio::import(here::here("daten/plastics.csv"), fill = TRUE)
```

### Die Daten kennenlernen

```{r class}
# Welche Datenklasse wird einem Datensatz zugewiesen?
class(plastics)
```

```{r view}
# Datensatz anschauen
View(plastics)
```

``` {r head}
# Die ersten sechs Zeilen
head(plastics)
```

``` {r tail}
# Die letzten sechs Zeilen
tail(plastics)
```

```{r colnames}
# Variablennamen
colnames(plastics)
```

```{r dimensionen}
# Betrachtung der Dimensionen
length(plastics) # Anzahl der Variablen
nrow(plastics) # Anzahl Zeilen
ncol(plastics) # Anzahl Spalten
dim(plastics) # Anzahl Zeilen & Spalten
```

``` {r summary}
# Zusammenfassung der Variablenstatistiken
summary(plastics)
```

``` {r structure}
# Zusammenfassung der Datensatzstruktur
str(plastics)
```

```{r column}
# Auf einzelne Spalten eines Datensatzes kann man über $ zugreifen
plastics$country

# Auf mehrere Spalten eines Datensatz muss man über [] zugreifen
plastics[, c("country", "year")]
```

```{r subset}
# Erstellung eines Subsets auf Basis von Bedingungen
subset(plastics, country == "Argentina" & year == 2020)
```
