---
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Notwendige Packages laden
pacman::p_load(
  glue,
  here,
  lubridate,
  rmarkdown,
  tidyverse
)
```

# Willkommen in der Report Fabrik

# Schritt 1: rmarkdown::render() Funktion

```{r}
# einen Report generieren
rmarkdown::render(input = "Report_Plastic.Rmd")
```


## Schritt 2:  Output Datei umbenennen

```{r}
# einen Report generieren und Output benennen
rmarkdown::render(
  input = "Report_Plastic.Rmd",
  output_file = "Report-Plastic_Europe"
)
```


# Schritt 3: Input vom Code trennen

## 3.1 Input definieren
```{r define-input}
set_rmd_name <- "Report_Plastic.Rmd"

# Einzelteile des Report Namens
set_continent <- "Asien"
set_report_name <- "Report-Plastic"
```

## 3.2 Dokumentnamen bauen
```{r build-document-name}
output_file_name <- glue::glue("{set_report_name}_{set_continent}")
```

## 3.3 Report mit Namen erstellen 
```{r}
# einen Report generieren und Output benennen
rmarkdown::render(
  input = here::here(set_rmd_name),
  output_file = output_file_name
)
```

# Schritt 4: YAML Optionen ändern 
```{r}
# einen Report generieren und Format definieren
rmarkdown::render(
  input = set_rmd_name,
  output_file = output_file_name,
  output_format = "pdf_document"
)
```


# Schritt 5: Parameter kennenlernen
  <!-- params: -->
  <!--   filter_continent: -->
  <!--     label: "Ausgewählte Region:" -->
  <!--     value: "alle Kontinente" -->
  <!--     input: select -->
  <!--     choices: ["Afrika", -->
  <!--               "Amerika", -->
  <!--               "Asien", -->
  <!--               "Europa", -->
  <!--               "Ozeanien", -->
  <!--               "alle Kontinente"] -->

# Schritt 6: Parameter nutzen

```{r example-europe}
rmarkdown::render(
  input = here::here("Report_Plastic.Rmd"),
  output_file = output_file_name,
  output_format = "html_document",
  params = list(filter_continent = "Europa")
)
```

```{r example-asia}
rmarkdown::render(
  input = here::here("Report_Plastic.Rmd"),
  output_file = output_file_name,
  output_format = "html_document",
  params = list(filter_continent = "Asien")
)
```

# Schritt 6: Parameter recyclen

```{r prep-continent-names}
continent_names <- audit_raw %>%
  dplyr::distinct(continent) %>%
  dplyr::pull(continent)
```

```{r walk-continent-names}
purrr::walk(
  .x = continent_names,
  .f = ~ rmarkdown::render(
    input = here::here(set_rmd_name),
    output_file = glue::glue("{set_report_name}_{.x}"),
    output_format = "html_document",
    # hier wird der Kontinentname übergeben
    params = list(filter_continent = .x)
  )
)
```
