# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  schedule:
    - cron: '00 8,9,10,11,12,13,14,15,16,17,18,19,20 * * *'
  workflow_dispatch:
 # push:
 # branches:
  # - main
name: STATUS_TEST

jobs:
  statustest:
    runs-on: ubuntu-20.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
          rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      
      - name: Install httr
        run: |
          install.packages('httr')
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: update all projects
        run: |
          options(crayon.enabled = TRUE)
          source('utils/apptesting.R')
        shell: Rscript {0}
